name: .NET Core deploy

on: push

jobs:
  deploy:
    strategy:
      matrix:
        configuration: [Release]

    runs-on: self-hosted

    steps:
     # - name: Download artifacts
      #  uses: actions/download-artifact@v3
       # with:
        #  name: WebApplication3.1.0.0.nupkg
          #path: ${{ env.Wap_Project_Path }}/AppPackages 
         # path: C:\Users\Admin\Projects\runner\actions-runner\_work\DotNet-WebApp\DotNet-WebApp\WebApplication3\WebApplication3\AppPackages

      - name: Download artifact
        id: download-artifact
        uses: actions/download-artifact@v3
        with:
          repo: https://github.com/pravesh-77/DotNet-WebApp
          workflow: dotnet-desktop.yml
          path: C:\Users\Admin\Projects\runner\actions-runner\_work\DotNet-WebApp\DotNet-WebApp\WebApplication3\WebApplication3
          search_artifacts: true
